# Generated by Django 2.2.6 on 2019-12-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0023_auto_20191203_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='big banner image to be displayed on your home page')),
                ('welcome_message', models.TextField(null=True, verbose_name='give you visitors a warm welcome')),
                ('about_club', models.TextField(null=True, verbose_name='about your club')),
                ('fstGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='fst gallery pic')),
                ('secGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='sec gallery pic')),
                ('trdGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='third gallery pic')),
                ('frthGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='fourth gallery pic')),
                ('fifGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='5th gallery pic')),
                ('sixthGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='6th gallery pic')),
                ('svthGpic', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='svthGpic gallery pic')),
                ('ResDjs1', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='Resdjs1 pic')),
                ('Resdj1name', models.CharField(max_length=50, verbose_name='name of 1st dj')),
                ('Resdj1pro', models.TextField(verbose_name='short profile of 1st resident dj')),
                ('ResDjs2', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='Resdjs2 pic')),
                ('Resdj2name', models.CharField(max_length=50, verbose_name='name of 2nd dj')),
                ('Resdj2pro', models.TextField(verbose_name='short profile of 2nd resident dj')),
                ('ResDjs3', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='Resdjs3 pic')),
                ('Resdj3name', models.CharField(max_length=50, verbose_name='name of 3rd dj')),
                ('Resdj3pro', models.TextField(verbose_name='short profile of 3rd resident dj')),
                ('ResDjs4', models.ImageField(null=True, upload_to='club/Homepage/', verbose_name='Resdjs4 pic')),
                ('Resdj4name', models.CharField(max_length=50, verbose_name='name of 4rth dj')),
                ('Resdj4pro', models.TextField(verbose_name='short profile of 4rth resident dj')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='profiles.BusinessProfile')),
            ],
        ),
    ]
