# Generated by Django 2.2.6 on 2019-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubsite', '0002_auto_20191205_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspagemodel',
            name='upcomming_event2',
            field=models.ImageField(null=True, upload_to='club/EventsPage', verbose_name='upcoming event 2'),
        ),
        migrations.AddField(
            model_name='eventspagemodel',
            name='upcomming_event3',
            field=models.ImageField(null=True, upload_to='club/EventsPage', verbose_name='upcoming event 3'),
        ),
        migrations.AddField(
            model_name='eventspagemodel',
            name='upcomming_event4',
            field=models.ImageField(null=True, upload_to='club/EventsPage', verbose_name='upcoming event 4'),
        ),
        migrations.AddField(
            model_name='eventspagemodel',
            name='upcomming_event5',
            field=models.ImageField(null=True, upload_to='club/EventsPage', verbose_name='upcoming event 5'),
        ),
        migrations.AddField(
            model_name='eventspagemodel',
            name='upcomming_event6',
            field=models.ImageField(null=True, upload_to='club/EventsPage', verbose_name='upcoming event 6'),
        ),
        migrations.AlterField(
            model_name='eventspagemodel',
            name='name_of_main_event',
            field=models.TextField(null=True, verbose_name='name of main event'),
        ),
        migrations.AlterField(
            model_name='eventspagemodel',
            name='upcomming_event1',
            field=models.ImageField(null=True, upload_to='club/EventsPage', verbose_name='upcoming event 1'),
        ),
    ]
