# Generated by Django 2.2.6 on 2019-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubsite', '0003_auto_20191205_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspagemodel',
            name='status_ep',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='status_tp',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='tonightmodel',
            name='status_tp',
            field=models.BooleanField(default=1),
        ),
    ]
