# Generated by Django 2.2.6 on 2019-12-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubsite', '0005_auto_20191205_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemodel',
            name='ResDjs2',
            field=models.ImageField(null=True, upload_to='club/HomePage/', verbose_name='Residentjs2 pic'),
        ),
        migrations.AlterField(
            model_name='homepagemodel',
            name='svthGpic',
            field=models.ImageField(null=True, upload_to='club/HomePage/', verbose_name='7thGpic gallery pic'),
        ),
    ]
