# Generated by Django 2.2.6 on 2019-12-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubsite', '0007_auto_20191209_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspagemodel',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tonightmodel',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
    ]
