# Generated by Django 2.2.6 on 2019-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='profile',
            new_name='logo',
        ),
    ]
