# Generated by Django 2.2.6 on 2019-11-12 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191112_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(default='chesanyama', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(choices=[('Mafikeng', 'Mafikeng northwest'), ('Mmabatho', 'Mmabatho northwest'), ('Rustenburg', 'Rustenburg northwest'), ('Potchefstroom', 'Potchefstroom northwest'), ('Klerksdorp', 'Klerksdorp northwest'), ('Johannesburg', 'Johannesburg Gauteng'), ('Krugersdorp', 'Krugersdorp Gauteng'), ('Pretoria', 'Pretoria Gauteng'), ('Randburg', 'Randburg Gauteng'), ('Randfontein', 'Randfontein Gauteng'), ('Roodepoort', 'Roodepoort Gauteng'), ('Soweto', 'Soweto Gauteng'), ('Springs', 'Springs Gauteng'), ('Vanderbijlpark', 'Vanderbijlpark Gauteng'), ('Vereeniging', 'Vereeniging Gauteng'), ('Germiston', 'Germiston Gauteng'), ('Carletonville', 'Carletonville Gauteng'), ('Brakpan', 'Brakpan Gauteng'), ('Boksburg', 'Boksburg Gauteng'), ('Benoni', 'Benoni Gauteng'), ('Bloemfontein', 'Bloemfontein FreeState'), ('Bethlehem', 'Bethlehem FreeState'), ('Jagersfontein', 'Jagersfontein FreeState'), ('Kroonstad', 'Kroonstad FreeState'), ('Odendaalsrus', 'Odendaalsrus FreeState'), ('Parys', 'Parys FreeState'), ('Phuthaditjhaba', 'Phuthaditjhaba FreeState'), ('Sasolburg', 'Sasolburg FreeState'), ('Virginia', 'Virginia FreeState'), ('Welkom', 'Welkom FreeState'), ('Alice', 'Alice EasternCape'), ('Butterworth', 'Butterworth EasternCape'), ('EastLondon', 'EastLondon EasternCape'), ('Graaff-Reinet', 'Graaff Reinet EasternCape'), ('Grahamstown', 'Grahamstown EasternCape'), ('King-William’s-Town', 'King-William’s-Town EasternCape'), ('Mthatha', 'Mthatha EasternCape'), ('Port-Elizabeth', 'Port-Elizabeth EasternCape'), ('Queenstown', 'Queenstown EasternCape'), ('Uitenhage', 'Uitenhage EasternCape'), ('Zwelitsha', 'Zwelitsha EasternCape'), ('Durban', 'Durban KwaZulu-Natal'), ('Empangeni', 'Empangeni KwaZulu-Natal'), ('Ladysmith', 'Ladysmith KwaZulu-Natal'), ('Newcastle', 'Newcastle KwaZulu-Natal'), ('Pietermaritzburg', 'Pietermaritzburg KwaZulu-Natal'), ('Pinetown', 'Pinetown KwaZulu-Natal'), ('Ulundi', 'Ulundi KwaZulu-Natal'), ('Umlazi', 'Umlazi KwaZulu-Natal'), ('Giyani', 'Giyani Limpopo'), ('Lebowakgomo', 'Lebowakgomo Limpopo'), ('Musina', 'Musina Limpopo'), ('Phalaborwa', 'Phalaborwa Limpopo'), ('Polokwane', 'Polokwane Limpopo'), ('Seshego', 'Seshego Limpopo'), ('Sibasa', 'Sibasa Limpopo'), ('Thabazimbi', 'Thabazimbi Limpopo'), ('Emalahleni', 'Emalahleni Mpumalanga'), ('Nelspruit', 'Nelspruit Mpumalanga'), ('Secunda', 'Secunda Mpumalanga'), ('Kimberley', 'Kimberley NorthernCape'), ('Kuruman', 'Kuruman NorthernCape'), ('PortNolloth', 'PortNolloth NorthernCape'), ('Cape-Town', 'Cape-Town WesternCape'), ('Bellville', 'Bellville WesternCape'), ('Constantia', 'Constantia WesternCape'), ('George', 'George WesternCape'), ('Hopefield', 'Hopefield WesternCape'), ('Oudtshoorn', 'Oudtshoorn WesternCape'), ('Paarl', 'Paarl WesternCape'), ('Simon’s-Town', 'Simon’s-Town WesternCape'), ('Stellenbosch', 'Stellenbosch WesternCape'), ('Swellendam', 'Swellendam WesternCape'), ('Worcester', 'Worcester WesternCape')], default='Mafikeng', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(default='we  do all the hair my brada and sister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='operating_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='province',
            field=models.CharField(choices=[('Northwest', 'Northwest'), ('Gauteng', 'Gauteng'), ('FreeState', 'FreeState'), ('EasternCape', 'EasternCape '), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('NorthernCape', 'NorthernCape'), ('WesternCape', 'WesternCape')], default='Northwest', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='recommendations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='streetname',
            field=models.CharField(default='setumontshiao', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='suburb',
            field=models.CharField(default='unit9', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='type_of_business',
            field=models.CharField(choices=[('Guest House', 'Guest House'), ('Club/Pub', 'Club/Pub'), ('Cosmatics', 'Cosmatics'), ('Salon', 'Salon'), ('Food', 'Food'), ('Beverage', 'liquor store'), ('Pharmacy', 'Pharmacy'), ('Dentist', 'Dentist')], default='salon', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(upload_to='static/businesslogos'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
