# Generated by Django 2.2.6 on 2019-11-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20191115_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
