# Generated by Django 2.2.6 on 2019-11-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20191116_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
