# Generated by Django 2.2.6 on 2019-11-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20191118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profilepic',
            field=models.ImageField(default='customer.jpg', upload_to='CustomerPics'),
        ),
    ]
