# Generated by Django 2.2.6 on 2019-11-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20191121_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(default='businesslogos/business.jpg', upload_to='businesslogos'),
        ),
    ]
