# Generated by Django 2.2.6 on 2019-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20191202_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cellPhone_number',
            field=models.IntegerField(verbose_name='cell phone number'),
        ),
    ]
