# Generated by Django 2.2.6 on 2019-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20191202_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='cellPhone_number',
            field=models.IntegerField(null=True, verbose_name='cell phone number'),
        ),
    ]
