# Generated by Django 2.2.6 on 2019-12-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20191202_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profilepic',
        ),
    ]
