# Generated by Django 2.2.6 on 2019-12-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_customerprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='Product1',
            field=models.ImageField(default='profileproducts/product.png', upload_to='profileproducts'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='Product2',
            field=models.ImageField(default='profileproducts/product.png', upload_to='profileproducts'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='Product3',
            field=models.ImageField(default='profileproducts/product.png', upload_to='profileproducts'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='Product4',
            field=models.ImageField(default='profileproducts/product.png', upload_to='profileproducts'),
        ),
    ]
