# Generated by Django 2.2.6 on 2019-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20191203_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='type_of_business',
            field=models.CharField(choices=[('Guest House', 'Guest House'), ('Club', 'Club/Pub'), ('Cosmatics', 'Cosmatics'), ('Salon', 'Salon'), ('BarberShop', 'Barber Shop'), ('Food', 'Food'), ('Liquor Store', 'liquor store')], max_length=200, null=True),
        ),
    ]
