# Generated by Django 2.2.6 on 2019-12-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20191207_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='type_of_business',
            field=models.CharField(choices=[('Guest House', 'Guest House'), ('Club', 'Club/Pub'), ('Cosmetics', 'Cosmetics'), ('Salon', 'Salon'), ('BarberShop', 'Barber Shop'), ('Food', 'Food'), ('LiquorStore', 'liquor store')], max_length=200, null=True),
        ),
    ]
