# Generated by Django 2.2.6 on 2019-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cususer',
            name='type',
        ),
        migrations.AddField(
            model_name='cususer',
            name='Account',
            field=models.CharField(choices=[('Business', 'Business'), ('Customer', 'Customer')], default='Customer', max_length=50),
        ),
    ]
