# Generated by Django 2.2.6 on 2019-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20191112_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cususer',
            name='userpic',
            field=models.ImageField(default='userpro.jpg', upload_to='userpics'),
        ),
    ]
