# Generated by Django 2.2.6 on 2019-12-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_cususer_typeofbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cususer',
            name='read_conditions',
            field=models.BooleanField(null=True, verbose_name='Are you sure youve read the terms and conditions of plentypot?'),
        ),
    ]
