# Generated by Django 2.2.6 on 2019-11-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_auto_20191116_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recommend_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Recommended by')),
                ('Recommended_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.BusinessProfile', verbose_name='Recommended Company')),
            ],
        ),
    ]
