# Generated by Django 2.2.6 on 2019-11-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='Recommended_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='profiles.BusinessProfile', verbose_name='Recommended Company'),
        ),
    ]
