# Generated by Django 2.2.6 on 2019-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonhomemodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salonpricesmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
