# Generated by Django 2.2.6 on 2019-12-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0003_salonpricesmodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonhomemodel',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salonpricesmodel',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
    ]
