# Generated by Django 2.2.6 on 2020-01-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20191213_2336'),
        ('Salon', '0004_auto_20191229_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style1des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style1pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style2des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style2pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style3des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style3pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style4des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style4pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style5des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style5pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style6des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style6pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style7des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style7pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style8des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style8pic',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style9des',
        ),
        migrations.RemoveField(
            model_name='salonpricesmodel',
            name='style9pic',
        ),
        migrations.CreateModel(
            name='ActualSalonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style1pic', models.ImageField(null=True, upload_to='Salon/Prices', verbose_name='upload 1st pic of the styles you are offering')),
                ('style1des', models.TextField(verbose_name='full details of the first style you are offering, include the price and variations')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actsalonprices', to='profiles.BusinessProfile')),
            ],
        ),
    ]
