# Generated by Django 2.2.6 on 2019-12-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticsHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='Big picture for your home page to welcome your vistors')),
                ('firstpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='Upload image to make your home page interesting')),
                ('secondpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='Upload image to make your home page interesting')),
                ('thirdpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='Upload image to make your home page interesting')),
                ('forthpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='Upload image to make your home page interesting')),
                ('fstworkpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='show people some of your best works')),
                ('fstworkdes', models.TextField(verbose_name='a little description about the first work picture')),
                ('secworkpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='show people some of your best works')),
                ('secworkdes', models.TextField(verbose_name='a little description about the sec work picture')),
                ('thirdworkpic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='show people some of your best works')),
                ('thirdworkdes', models.TextField(verbose_name='a little description about the third work picture')),
                ('fstteampic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='the picture of the first team member')),
                ('fstteamdes', models.TextField(verbose_name='a little description about the fst team member')),
                ('secteampic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='the picture of the second team member')),
                ('secteamdes', models.TextField(verbose_name='a little description about the second team member')),
                ('thirdteampic', models.ImageField(null=True, upload_to='Cosmetics/Homepage', verbose_name='the picture of the third team member')),
                ('thirdteamdes', models.TextField(verbose_name='a little description about the third team member')),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticsWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstworkpic', models.ImageField(null=True, upload_to='Cosmetics/Workpage', verbose_name='show your visitors more of the work you do,upload first picture')),
                ('fstworkdescription', models.TextField(verbose_name='type details about the first picture, especially the price')),
                ('secworkpic', models.ImageField(null=True, upload_to='Cosmetics/Workpage', verbose_name='show your visitors more of the work you do,upload second picture')),
                ('secworkdescription', models.TextField(verbose_name='type details about the second picture, especially the price')),
                ('thirdworkpic', models.ImageField(null=True, upload_to='Cosmetics/Workpage', verbose_name='show your visitors more of the work you do,upload third picture')),
                ('thirdworkdescription', models.TextField(verbose_name='type details about the third picture, especially the price')),
                ('fourthworkpic', models.ImageField(null=True, upload_to='Cosmetics/Workpage', verbose_name='show your visitors more of the work you do,upload fourth picture')),
                ('fourthworkdescription', models.TextField(verbose_name='type details about the fourth picture, especially the price')),
                ('fifthworkpic', models.ImageField(null=True, upload_to='Cosmetics/Workpage', verbose_name='show your visitors more of the work you do,upload fifth picture')),
                ('fifthworkdescription', models.TextField(verbose_name='type details about the fifth picture, especially the price')),
                ('sixthworkpic', models.ImageField(null=True, upload_to='Cosmetics/Workpage', verbose_name='show your visitors more of the work you do,upload sixth picture')),
                ('sixthworkdescription', models.TextField(verbose_name='type details about the sixth picture, especially the price')),
            ],
        ),
    ]
