# Generated by Django 2.2.6 on 2019-12-08 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20191207_0715'),
        ('Cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticshomepage',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cosmeticshome', to='profiles.BusinessProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosmeticswork',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='priceshome', to='profiles.BusinessProfile'),
            preserve_default=False,
        ),
    ]
