# Generated by Django 2.2.6 on 2019-12-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0002_auto_20191208_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticswork',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cosmeticswork', to='profiles.BusinessProfile'),
        ),
    ]
