# Generated by Django 2.2.6 on 2019-12-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0003_auto_20191208_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticshomepage',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='cosmeticswork',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
