# Generated by Django 2.2.6 on 2019-12-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0004_auto_20191209_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticshomepage',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cosmeticswork',
            name='PageComplete',
            field=models.BooleanField(default=False),
        ),
    ]
