# Generated by Django 2.2.6 on 2020-01-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20191213_2336'),
        ('Cosmetics', '0005_auto_20191229_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='fifthworkdescription',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='fifthworkpic',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='fourthworkdescription',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='fourthworkpic',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='fstworkdescription',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='fstworkpic',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='secworkdescription',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='secworkpic',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='sixthworkdescription',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='sixthworkpic',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='thirdworkdescription',
        ),
        migrations.RemoveField(
            model_name='cosmeticswork',
            name='thirdworkpic',
        ),
        migrations.CreateModel(
            name='ActualCosWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workpic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the first item on your menu')),
                ('Workdes', models.TextField(blank=True, null=True, verbose_name='a short description of the first picture on your menu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualCosWork', to='profiles.BusinessProfile')),
            ],
        ),
    ]
