# Generated by Django 2.2.6 on 2019-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='body',
            field=models.TextField(default='ya hlangana'),
            preserve_default=False,
        ),
    ]
