# Generated by Django 2.2.6 on 2019-11-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Responses', '0003_auto_20191116_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.BusinessProfile'),
        ),
    ]
