# Generated by Django 2.2.6 on 2019-12-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0026_auto_20191208_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMenuPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu1pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the first item on your menu')),
                ('menu1des', models.TextField(blank=True, null=True, verbose_name='a short description of the first picture on your menu')),
                ('menu2pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the second item on your menu')),
                ('menu2des', models.TextField(blank=True, null=True, verbose_name='a short description of the second picture on your menu')),
                ('menu3pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the third item on your menu')),
                ('menu3des', models.TextField(blank=True, null=True, verbose_name='a short description of the third picture on your menu')),
                ('menu4pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the fourth item on your menu')),
                ('menu4des', models.TextField(blank=True, null=True, verbose_name='a short description of the fourth picture on your menu')),
                ('menu5pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the fifth item on your menu')),
                ('menu5des', models.TextField(blank=True, null=True, verbose_name='a short description of the fifth picture on your menu')),
                ('menu6pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the sixth item on your menu')),
                ('menu6des', models.TextField(blank=True, null=True, verbose_name='a short description of the sixth picture on your menu')),
                ('menu7pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the seventh item on your menu')),
                ('menu7des', models.TextField(blank=True, null=True, verbose_name='a short description of the seventh picture on your menu')),
                ('menu8pic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the eighth item on your menu')),
                ('menu8des', models.TextField(blank=True, null=True, verbose_name='a short description of the eighth picture on your menu')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodmenu', to='profiles.BusinessProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FoodHomePageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload an eye catching large picture to impress visitors')),
                ('welcomeMes', models.TextField(verbose_name='Write a warm welcome message for your visitors')),
                ('item1pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the first picture to display on your home page,usually a dish')),
                ('item1name', models.CharField(max_length=100, verbose_name=' the name of the first picture you were instructed to upload')),
                ('item1description', models.TextField(verbose_name='a short description of the first picture you were instructed to upload')),
                ('item2pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the second picture to display on your home page,usually a dish')),
                ('item2name', models.CharField(max_length=100, verbose_name=' the name of the second picture you were instructed to upload')),
                ('item2description', models.TextField(verbose_name='a short description of the second picture you were instructed to upload')),
                ('item3pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the third picture to display on your home page,usually a dish')),
                ('item3name', models.CharField(max_length=100, verbose_name=' the name of the third picture you were instructed to upload')),
                ('item3description', models.TextField(verbose_name='a short description of the third picture you were instructed to upload')),
                ('item4pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the fourth picture to display on your home page,usually a dish')),
                ('item4name', models.CharField(max_length=100, verbose_name=' the name of the fourth picture you were instructed to upload')),
                ('item4description', models.TextField(verbose_name='a short description of the fourth picture you were instructed to upload')),
                ('item5pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the fifth picture to display on your home page,usually a dish')),
                ('item5name', models.CharField(max_length=100, verbose_name=' the name of the fifth picture you were instructed to upload')),
                ('item5description', models.TextField(verbose_name='a short description of the fifth picture you were instructed to upload')),
                ('item6pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the sixth picture to display on your home page,usually a dish')),
                ('item6name', models.CharField(max_length=100, verbose_name=' the name of the sixth picture you were instructed to upload')),
                ('item6description', models.TextField(verbose_name='a short description of the sixth picture you were instructed to upload')),
                ('item7pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the seventh picture to display on your home page,usually a dish')),
                ('item7name', models.CharField(max_length=100, verbose_name=' the name of the seventh picture you were instructed to upload')),
                ('item7description', models.TextField(verbose_name='a short description of the seventh picture you were instructed to upload')),
                ('item8pic', models.ImageField(null=True, upload_to='Foodshop/Homepage', verbose_name='Upload the eighth picture to display on your home page,usually a dish')),
                ('item8name', models.CharField(max_length=100, verbose_name=' the name of the eighth picture you were instructed to upload')),
                ('item8description', models.TextField(verbose_name='a short description of the eighth picture you were instructed to upload')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodhome', to='profiles.BusinessProfile')),
            ],
        ),
    ]
