# Generated by Django 2.2.6 on 2019-12-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhomepagemodel',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='fullmenupagemodel',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
