# Generated by Django 2.2.6 on 2020-01-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodStore', '0003_auto_20191229_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullmenupagemodel',
            old_name='menu1des',
            new_name='menudes',
        ),
        migrations.RenameField(
            model_name='fullmenupagemodel',
            old_name='menu1pic',
            new_name='menupic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu2des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu2pic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu3des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu3pic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu4des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu4pic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu5des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu5pic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu6des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu6pic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu7des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu7pic',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu8des',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menu8pic',
        ),
    ]
