# Generated by Django 2.2.6 on 2020-01-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20191213_2336'),
        ('FoodStore', '0004_auto_20200120_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menudes',
        ),
        migrations.RemoveField(
            model_name='fullmenupagemodel',
            name='menupic',
        ),
        migrations.CreateModel(
            name='ActualMenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menupic', models.ImageField(blank=True, null=True, upload_to='Foodshop/Foodmenu', verbose_name='Upload the picture of the first item on your menu')),
                ('menudes', models.TextField(blank=True, null=True, verbose_name='a short description of the first picture on your menu')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actualmenudata', to='profiles.BusinessProfile')),
            ],
        ),
    ]
