# Generated by Django 2.2.6 on 2019-12-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiquorStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquorsalesmodel',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquorsales', to='profiles.BusinessProfile'),
        ),
    ]
