# Generated by Django 2.2.6 on 2019-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiquorStore', '0002_auto_20191207_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle1',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle2',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle3',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle4',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle5',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle6',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle7',
        ),
        migrations.RemoveField(
            model_name='liquorhomepagemodel',
            name='bottle8',
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer1des',
            field=models.TextField(null=True, verbose_name='price description for second beers/ciders pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer2des',
            field=models.TextField(null=True, verbose_name='price description for third beers/ciders pic '),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer3des',
            field=models.TextField(null=True, verbose_name='price description for fourth beers/ciders pic '),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer4des',
            field=models.TextField(null=True, verbose_name='price description for fifth beers/ciders pic '),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer6des',
            field=models.TextField(null=True, verbose_name='price description for sixth beers/ciders pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer7des',
            field=models.TextField(null=True, verbose_name='price description for seventh beers/ciders pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='beer8des',
            field=models.TextField(null=True, verbose_name='price description for eighth beers/ciders pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine1',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='first pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine1des',
            field=models.TextField(null=True, verbose_name='price description for first wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine2',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='second pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine2des',
            field=models.TextField(null=True, verbose_name='price description for sixth wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine3',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='third pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine3des',
            field=models.TextField(null=True, verbose_name='price description for third wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine4',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='fourth pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine4des',
            field=models.TextField(null=True, verbose_name='price description for fifth wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine5',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='fifth pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine5des',
            field=models.TextField(null=True, verbose_name='price description for fifth wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine6',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='sixth pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine7',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='seventh pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine7des',
            field=models.TextField(null=True, verbose_name='price description for seventh wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine8',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='8th pic under wines/champagne'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='wine8des',
            field=models.TextField(null=True, verbose_name='price description for eighth wines/champagne pic'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale1des',
            field=models.TextField(null=True, verbose_name='sale description for item1'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale2des',
            field=models.TextField(null=True, verbose_name='sale description for item2'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale3des',
            field=models.TextField(null=True, verbose_name='sale description for item3'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale4des',
            field=models.TextField(null=True, verbose_name='sale description for item4'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale5des',
            field=models.TextField(null=True, verbose_name='sale description for item5'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale6des',
            field=models.TextField(null=True, verbose_name='sale description for item6'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale7des',
            field=models.TextField(null=True, verbose_name='sale description for item7'),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='sale8des',
            field=models.TextField(null=True, verbose_name='sale description for item8'),
        ),
    ]
