# Generated by Django 2.2.6 on 2019-12-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiquorStore', '0003_auto_20191207_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle1',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='first pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle1des',
            field=models.TextField(null=True, verbose_name='price description for first Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle2',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='second pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle2des',
            field=models.TextField(null=True, verbose_name='price description for sec Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle3',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='third pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle3des',
            field=models.TextField(null=True, verbose_name='price description for third Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle4',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='fourth pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle5',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='fifth pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle5des',
            field=models.TextField(null=True, verbose_name='price description for fifth Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle6',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='sixth pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle6des',
            field=models.TextField(null=True, verbose_name='price description for sixth Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle7',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='seventh pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle7des',
            field=models.TextField(null=True, verbose_name='price description for seventh Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle8',
            field=models.ImageField(null=True, upload_to='LiquorStore/LiquorHome/', verbose_name='8th pic under Liquor/Spirits'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottle8des',
            field=models.TextField(null=True, verbose_name='price description for eighth Liquor/Spirits pic'),
        ),
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='bottledes',
            field=models.TextField(null=True, verbose_name='price description for fifth Liquor/Spirits pic'),
        ),
    ]
