# Generated by Django 2.2.6 on 2019-12-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiquorStore', '0005_auto_20191208_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorhomepagemodel',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='liquorsalesmodel',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
